language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="9ae51849-00d8-4559-9cc8-90a0dbcbf5f7"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vasiliy.krasov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always